# Environmental secrets are only available for that specific environment.
development:
  mail_smtp:
    # address: 'smtp.gmail.com'
    # port: 587
    # user_name: 'thinkbizcompany@gmail.com'
    # password: 'Thinkbiz@123'
    # enable_starttls_auto: true
    # authentication: :plain
    # from_email: 'thinkbizcompany@gmail.com'
    # to_email: 'dhimandeepa007@gmail.com'
  react_app_host: "http://localhost:3000/survey/token"
test:
  elastic_search_host: "https://vpc-right-on-dev-ojxui3vbpot32mxprkfazm7iji.ap-northeast-1.es.amazonaws.com"
